# .github/workflows/build-and-push-frontend.yml
name: Build and Push Frontend to ECR

on:
  push:
    branches:
      - main # Trigger this workflow on pushes to the 'main' branch of frontend repo

env:
  # Environment variables for AWS and ECR
  # AWS_REGION is now passed directly to the configure-aws-credentials action
  ECR_REPOSITORY: my-frontend-app # Name of your ECR repository

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use a fresh Ubuntu runner for each job

    permissions:
      id-token: write # Required for OIDC authentication (if using IAM roles for ECR push)
      contents: read  # Required to checkout the repository code

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Action to clone your GitHub repository (my-frontend-app)

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4 # Action for OIDC authentication
        with:
          # Use Access Key/Secret Key for authentication
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # Directly use secret

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2 # Action to log Docker into ECR

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }} # Get ECR registry URL from login step
          IMAGE_TAG: latest # Tag for your Docker image
          REACT_APP_BACKEND_URL: https://theproductpeek.shop/api/ # Use EC2_HOST secret
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }} # <--- ADDED THIS LINE
          AWS_REGION: ${{ secrets.AWS_REGION }} # <--- ADDED THIS LINE
        run: |
          # Build the Docker image, passing the REACT_APP_BACKEND_URL as a build argument
          docker buildx build --platform linux/amd64 --build-arg REACT_APP_BACKEND_URL="${REACT_APP_BACKEND_URL}" -t "${AWS_ACCOUNT_ID}".dkr.ecr."${AWS_REGION}".amazonaws.com/my-frontend-app:latest --no-cache --force-rm --push .

          echo "Frontend image pushed to ECR: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
